# Generated by Django 4.2.7 on 2025-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_duplicate_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('HOTEL', 'Hotel')], default='USER', max_length=10),
        ),
    ]
