# Generated by Django 4.2.7 on 2025-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotelprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='hotel_stars',
            field=models.IntegerField(default=0),
        ),
    ]
