# Generated by Django 4.2.7 on 2025-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hotelprofile_hotel_image_hotelprofile_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='availability_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='availability_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of features (e.g., Free WiFi, Pool, Gym)', null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
