# Generated by Django 4.2.7 on 2025-07-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hotelprofile_availability_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprofile',
            name='hotel_image',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('hotel_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.hotelprofile')),
            ],
        ),
    ]
