# Generated by Django 4.2.7 on 2025-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance_to_center',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='guest_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
