# Generated by Django 4.2.7 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_amenities_hotel_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
