# Generated by Django 4.2.7 on 2025-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_favoritehotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.IntegerField(default=1),
        ),
    ]
