# Generated by Django 4.2.7 on 2025-07-24 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0011_feature_and_hotel_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'HOTEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
