# Generated by Django 4.2.7 on 2025-07-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0012_alter_hotel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'HOTEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
