# Generated by Django 4.2.7 on 2025-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='hotel_images/'),
        ),
    ]
